### ISSUE TITLE
Followers screen not showing followers/following due to error in JQuery Selector

### ISSUE THREAD

**Issue by acterry** [bmalnad/btcjamhelper#5]
On lines 1326 and 1327 in helper.js, totalfollowers and totalfollowing are being calculated as NAN. 

Looks like the page structure changed on the Followers screen and you can no longer see followers and following.

```
totalfollowers = parseInt($("#body > div:nth-child(4) > div > div > div.col-md-3 > div > div.row.profile-numbers.border-top > div:nth-child(1) > div > div:nth-child(2) > p").text().trim());
totalfollowing = parseInt($("#body > div:nth-child(4) > div > div > div.col-md-3 > div > div.row.profile-numbers.border-top > div:nth-child(2) > div > div:nth-child(2) > p").text().trim());

```

**Comment by bmalnad** [comment]
Thanks!  I'll get a fix out asap.

**Comment by acterry** [comment]
I'm working on it now

**Comment by bmalnad** [comment]
Even better :-D

**Comment by tbenton** [comment]
Look forward to the fix.  Thanks.

**Comment by acterry** [comment]
Just issued PR https://github.com/bmalnad/btcjamhelper/pull/6

**Comment by bmalnad** [comment]
Merged and released.  Thanks!
